### ISSUE TITLE
Transactions in Jooq

### ISSUE THREAD

**Issue by itboy87** [quarkiverse/quarkus-jooq#14]
I tried this jooq transaction not respecting the @Transactional annotation.

What about the development of this extension? It's almost a month and no work on it?

**Comment by angrymango** [comment]
Hi @itboy87 thanks for your feedback. Can you provide some specific information so I can re-create the issue you are facing?

When I follow the instructions here https://quarkus.io/guides/transaction I don't have any issue using the `@Transactional` annotation.

**Comment by angrymango** [comment]
Closing as I haven't received a reproducible test case.
