### ISSUE TITLE
Add a <description> to the runtime artifacts´ pom.xml 

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-jooq#15]
The generated metadata is reusing the `<description>` from the parent pom. It should have its own:

```json
    {
      "name": "Quarkus jOOQ - Runtime",
      "description": "Parent POM for Quarkiverse projects that includes the default release and artifact publishing related\n    configuration",
}
```

**Comment by angrymango** [comment]
@gastaldi hopefully this addressed by this commit: https://github.com/quarkiverse/quarkus-jooq/commit/7d0b4410a3503faf41fb4864ee5fa6b1d72d385c

**Comment by gastaldi** [comment]
@angrymango it does, it should be okay in the next extension release. Thank you!
