### ISSUE TITLE
how to audio player implement in android this code audio auto play and end is error occur.

### ISSUE THREAD

**Issue by Pawanyadav1** [quarkiverse/quarkus-jooq#49]
XML :  
 <com.arges.sepan.argmusicplayer.PlayerViews.ArgPlayerFullScreenView
                    android:id="@+id/argmusicplayer"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:padding="5dp"
                    android:visibility="visible" />

JAVA :

 holder.postrelative.setVisibility(View.GONE);
            holder.relVideo.setVisibility(View.VISIBLE);
            holder.cardAudio.setVisibility(View.VISIBLE);
            holder.relSHowVideos.setVisibility(View.GONE);
           // holder.imgDownload2.setVisibility(View.GONE);
           // holder.postrelative.setVisibility(View.GONE);
          //  holder.relVideo.setVisibility(View.VISIBLE);
          //  holder.cardAudio.setVisibility(View.GONE);
           // holder.relSHowVideos.setVisibility(View.VISIBLE);
            // holder.relativeAudio.setBackground(R.drawable.);

            Glide.with(mContext).load(homeDataModel.getPath() + homeDataModel.getThumbnail_image()).into(holder.imgAudio);
            String url = "https://www.gotinenstranan.com/songs/joan-baez-north-country-blues.mp3";
            audio = ArgAudio.createFromURL(homeDataModel.getTitle(), homeDataModel.getTitle(), homeDataModel.getPath() + homeDataModel.getFile());

            holder.argmusicplayer.play(audio);
            holder.argmusicplayer.seekTo(10000);
            holder.argmusicplayer.setEnabled(true);

**Comment by ThoSap** [comment]
Hi, I think you opened this ticket at the wrong repo. Quarkus jOOQ has nothing to do with Android development.

**Comment by angrymango** [comment]
This is not related to Quarkus jOOQ
